### ISSUE TITLE
Line highlighting should be behind arrow

### ISSUE THREAD

**Issue by caco3** [AlanDeSmet/human-resource-machine-viewer#9]
As is now, the line highlighting is in front of the arrow.
Is there a way to draw the arrow in front of the highlighted line?
![final1](https://cloud.githubusercontent.com/assets/1783586/12533227/6d8c67d0-c229-11e5-8628-8a3f73a714d8.png)

**Comment by sixlettervariables** [comment]
You could probably edit the CSS and add a z-index to achieve that effect:

``` css
.hrmcode .jumppath {
    stroke: #8d8dc1;
    stroke-width: 0.3em;
    fill: transparent;
        z-index: 2;
}
.hrmcode .jumppatharrow {
    stroke: #8d8dc1;
    fill: #8d8dc1;
    stroke-width: 0;
        z-index: 2;
}
```

Although [my implementation](http://christopherwatford.com/hrmsandbox/) does not seem to suffer that graphical error (click the Eye icon to view).

**Comment by caco3** [comment]
Hi
Maybe it is because I have put it into a div myself and also use other CSS lines.
Your suggestion didnt help, but I found out that I have to put the table into the background:

``` css
.hrmcode table {
        border-collapse: collapse;
        position: absolute;
        z-index: -1;
}
```

Than you for your quick response and the hint!
